// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').controller('HeaderCtrl', [
    '$scope', 'socket', '$location', '$window', '$cookies', function($scope, socket, $location, $window, $cookies) {
      $scope.socketStatus = 'Closed';
      $scope.poorSignal = 200;
      socket.forward('port-opened', $scope);
      socket.forward('port-closed', $scope);
      socket.forward('disconnect', $scope);
      $scope.$on('socket:port-opened', function() {
        return $scope.socketStatus = 'Opened';
      });
      $scope.$on('socket:disconnect', function() {
        $scope.socketStatus = 'Closed';
        return $scope.poorSignal = 200;
      });
      socket.forward('data', $scope);
      $scope.$on('socket:data', function(ev, data) {
        if (data.poorSignal != null) {
          return $scope.poorSignal = data.poorSignal;
        }
      });
      return $scope.getClass = function(path) {
        return $location.path() === path;
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=Header.map
*/
