// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').controller('MainCtrl', [
    '$scope', 'socket', function($scope, socket) {
      $scope.meditation = $scope.attention = $scope.delta = $scope.theta = $scope.lowAlpha = $scope.highAlpha = $scope.lowBeta = $scope.highBeta = $scope.lowGamma = $scope.$highGamma = $scope.rawEeg = 0;
      $scope.isRecordingStarted = false;
      socket.forward('data', $scope);
      return $scope.$on('socket:data', function(ev, data) {
        if (data.poorSignal != null) {
          $scope.poorSignal = data.poorSignal;
        }
        if ($scope.poorSignal < 50) {
          if (data != null ? data.rawEeg : void 0) {
            return $scope.rawEeg = data.rawEeg;
          } else {
            $scope.meditation = data.meditation || $scope.meditation;
            $scope.attention = data.attention || $scope.attention;
            $scope.delta = data.delta || $scope.delta;
            $scope.theta = data.theta || $scope.theta;
            $scope.lowAlpha = data.lowAlpha || $scope.lowAlpha;
            $scope.highAlpha = data.highAlpha || $scope.highAlpha;
            $scope.lowBeta = data.lowBeta || $scope.lowBeta;
            $scope.highBeta = data.highBeta || $scope.highBeta;
            $scope.lowGamma = data.lowGamma || $scope.lowGamma;
            return $scope.highGamma = data.highGamma || $scope.highGamma;
          }
        }
      });
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
