// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Filter: entities', function() {
    var entities;
    beforeEach(module('twimpressApp'));
    entities = {};
    beforeEach(inject(function($filter) {
      return entities = $filter('entities');
    }));
    return it('should return the input prefixed with "entities filter:"', function() {
      var text;
      text = 'angularjs';
      return expect(entities(text)).toBe('entities filter: ' + text);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=entities.map
*/
