// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Filter: setHeightCss', function() {
    var setHeightCss;
    beforeEach(module('twimpressApp'));
    setHeightCss = {};
    beforeEach(inject(function($filter) {
      return setHeightCss = $filter('setHeightCss');
    }));
    return it('should return the input prefixed with "setHeightCss filter:"', function() {
      var text;
      text = 'angularjs';
      return expect(setHeightCss(text)).toBe('setHeightCss filter: ' + text);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=setHeightCss.map
*/
