// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: gaugechart', function() {
    var scope;
    beforeEach(module('twimpressApp'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<gaugechart></gaugechart>');
      element = $compile(element)(scope);
      return expect(element.text()).toBe('this is the gaugechart directive');
    }));
  });

}).call(this);

/*
//@ sourceMappingURL=gaugechart.map
*/
