// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: EvaluatetwittsCtrl', function() {
    var EvaluatetwittsCtrl, scope;
    beforeEach(module('twimpressApp'));
    EvaluatetwittsCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return EvaluatetwittsCtrl = $controller('EvaluatetwittsCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=evaluateTweets.map
*/
