// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: HeaderCtrl', function() {
    var HeaderCtrl, scope;
    beforeEach(module('twimpressApp'));
    HeaderCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return HeaderCtrl = $controller('HeaderCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=Header.map
*/
