// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').filter('entities', [
    '$sce', function($sce) {
      return function(input, entities) {
        var entry, i, ind, index_map, result, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
        index_map = {};
        if (entities != null ? entities.urls : void 0) {
          _ref = entities.urls;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            entry = _ref[_i];
            index_map[entry.indices[0]] = [entry.indices[1], "<a href='" + entry.expanded_url + "'>" + entry.url + "</a>"];
          }
        }
        if (entities != null ? entities.hashtags : void 0) {
          _ref1 = entities.hashtags;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            entry = _ref1[_j];
            index_map[entry.indices[0]] = [entry.indices[1], "<a href='http://twitter.com/search?q=#" + (encodeURI(entry.text)) + "'>#" + entry.text + "</a>"];
          }
        }
        if (entities != null ? entities.user_mentions : void 0) {
          _ref2 = entities.user_mentions;
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            entry = _ref2[_k];
            index_map[entry.indices[0]] = [entry.indices[1], "<a href='http://twitter.com/" + entry.screen_name + "'>@" + entry.screen_name + "</a>"];
          }
        }
        result = "";
        i = 0;
        while (i < input.length) {
          ind = index_map[i];
          if (ind) {
            result += ind[1];
            i = ind[0];
          } else {
            result += input[i];
            i++;
          }
        }
        return $sce.trustAsHtml(result);
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=entities.map
*/
