// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').filter('setHeightCss', function() {
    return function(input) {
      return "width: " + input + "%";
    };
  });

}).call(this);

/*
//@ sourceMappingURL=setHeightCss.map
*/
