// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').directive('signal', function() {
    return {
      restrict: 'A',
      scope: {
        signal: "@"
      },
      link: function(scope, element, attrs) {
        element.addClass("signal-status");
        return scope.$watch("signal", function(value) {
          var classToAdd;
          value = +value;
          classToAdd = (function() {
            switch (false) {
              case !(100 <= value && value < 200):
                return "connection-signal-poor-1";
              case !(50 <= value && value < 100):
                return "connection-signal-poor-2";
              case !(0 < value && value < 50):
                return "connection-signal-poor-3";
              case value !== 0:
                return "connection-connected";
              default:
                return "connection-disconnected";
            }
          })();
          if (scope.currentSignalClass) {
            element.removeClass(scope.currentSignalClass);
          }
          scope.currentSignalClass = classToAdd;
          return element.addClass(classToAdd);
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=signal.map
*/
