// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('twimpressApp').directive('twitterSignin', [
    '$http', '$window', '$compile', '$rootScope', function($http, $window, $compile, $rootScope) {
      return {
        restrict: 'A',
        link: function(scope, element) {
          var signInButtonTpl, welcomeUserTpl;
          signInButtonTpl = '<button ng-click="signIn()" class="btn btn-mini btn-signin"><i class="fa fa-twitter"></i> Sign in</button>';
          welcomeUserTpl = '<img ng-src="{{profileImg}}" class="profile-img" /> Welcome, {{screenName}}';
          scope.signIn = function() {
            return $window.location = 'http://127.0.0.1:8080/twauth';
          };
          return $http.jsonp('http://127.0.0.1:8080/is-signed?callback=JSON_CALLBACK').success(function(response) {
            var resultTemplate;
            resultTemplate = response.isSigned ? welcomeUserTpl : signInButtonTpl;
            if (response.isSigned) {
              scope.screenName = response.screenName;
              scope.profileImg = response.profileImg;
              $rootScope.$emit("signed");
            }
            element.html(resultTemplate);
            return $compile(element.contents())(scope);
          });
        }
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=twitter-signin.map
*/
